create table book(
    id serial primary key,
    title varchar not null,
    author varchar,
    _year integer
);

insert into book(title, author, _year) values
    ('Pride and Prejudice', 'Jane Austen', 1813),
    ('To Kill a Mockingbird', 'Harper Lee', 1960),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 1925),
    ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967),
    ('In Cold Blood', 'Truman Capote', 1965),
    ('Wide Sargasso Sea', 'Jean Rhys', 1966),
    ('Brave New World', 'Aldous Huxley', 1932),
    ('I Capture The Castle', 'Dodie Smith', 1948),
    ('Jane Eyre', 'Charlotte Bronte', 1847),
    ('Crime and Punishment', 'Fyodor Dostoevsky', 1866),
    ('The Secret History', 'Donna Tartt', 1992),
    ('The Call of the Wild', 'Jack London', 1903),
    ('The Chrysalids', 'John Wyndham', 1955),
    ('Persuasion', 'Jane Austen', 1818),
    ('Moby-Dick', 'Herman Melville', 1851),
    ('The Lion, the Witch and the Wardrobe', 'C.S. Lewis', 1950),
    ('To the Lighthouse', 'Virginia Woolf', 1927),
    ('The Death of the Heart', 'Elizabeth Bowen', 1938),
    ('Tess of the d''Urbervilles', 'Thomas Hardy', 1891),
    ('Frankenstein', 'Mary Shelley', 1823),
    ('The Master and Margarita', 'Mikhail Bulgakov', 1966),
    ('The Go-Between', 'L. P. Hartley', 1953),
    ('One Flew Over the Cuckoo''s Nest', 'Ken Kesey', 1962),
    ('Nineteen Eighty-Four', 'George Orwell', 1949),
    ('Buddenbrooks', 'Thomas Mann', 1901),
    ('The Grapes of Wrath', 'John Steinbeck', 1939),
    ('The Code of the Woosters', 'P. G. Wodehouse', 1938),
    ('Dracula', 'Bram Stoker', 1897),
    ('The Lord of the Rings', 'J. R. R. Tolkien', 1954),
    ('The Adventures of Huckleberry Finn', 'Mark Twain', 1884),
    ('Great Expectations', 'Charles Dickens', 1860),
    ('Catch-22', 'Joseph Heller', 1961),
    ('The Age of Innocence', 'Edith Wharton', 1920),
    ('Things Fall Apart', 'Chinua Achebe', 1958),
    ('Middlemarch', 'George Eliot', 1871),
    ('Midnight''s Children', 'Salman Rushdie', 1981),
    ('Vanity Fair', 'William Makepeace Thackeray', 1847),
    ('Brideshead Revisited', 'Evelyn Waugh', 1945),
    ('The Catcher in the Rye', 'J.D. Salinger', 1951),
    ('Alice''sAdventures in Wonderland', 'Lewis Carroll', 1865),
    ('The Mill on the Floss', 'George Eliot', 1860),
    ('Barchester Towers', 'Anthony Trollope', 1857),
    ('Another Country', 'James Baldwin', 1962),
    ('Les Miserables', 'Victor Hugo', 1862),
    ('Charlie and the Chocolate Factory', 'Roald Dahl', 1964),
    ('The Outsiders', 'S. E. Hinton', 1967),
    ('The Count of Monte Cristo', 'Alexandre Dumas', 1844),
    ('Ulysses', 'James Joyce', 1922),
    ('East of Eden', 'John Steinbeck', 1952),
    ('The Brothers Karamazov', 'Fyodor Dostoyevsky', 1880),
    ('Lolita', 'Vladimir Nabokov', 1955),
    ('The Secret Garden', 'Frances Hodgson Burnett', 1911),
    ('Scoop', 'Evelyn Waugh', 1938),
    ('A Tale of Two Cities', 'Charles Dickens', 1859),
    ('Diary of a Nobody', 'George Grossmith and Weedon Grossmith', 1892),
    ('Anna Karenina', 'Leo Tolstoy', 1878),
    ('The Betrothed', 'Alessandro Manzoni', 1827),
    ('Orlando', 'Virginia Woolf', 1928),
    ('Atlas Shrugged', 'Ayn Rand', 1957),
    ('The Time Machine', 'H. G. Wells', 1895),
    ('The Forsyte Saga', 'John Galsworthy', 1922),
    ('Travels with Charley', 'John Steinbeck', 1962),
    ('Tropic of Cancer', 'Henry Miller', 1934),
    ('Women in Love', 'D. H. Lawrence', 1920),
    ('Staying On', 'Paul Scott', 1977),
    ('The Wind in the Willows', 'Kenneth Grahame', 1908),
    ('My Antonia', 'Willa Cather', 1918),
    ('Wuthering Heights', 'Emily Bronte', 1847),
    ('Perfume', 'Patrick Sueskind', 1985),
    ('War and Peace', 'Leo Tolstoy', 1867),
    ('Of Human Bondage', 'Somerset Maugham', 1915),
    ('Bleak House', 'Charles Dickens', 1853),
    ('Lost Illusions', 'Honore de Balzac', 1837),
    ('Breakfast of Champions', 'Kurt Vonnegut', 1973),
    ('A Christmas Carol', 'Charles Dickens', 1843),
    ('Silas Marner', 'George Eliot', 1861),
    ('Mrs Dalloway', 'Virginia Woolf', 1925),
    ('Little Women', 'Louisa May Alcott', 1868),
    ('The Sea, The Sea', 'Iris Murdoch', 1978),
    ('Zen and the Art of Motorcycle Maintenance', 'Robert Pirsig', 1974),
    ('The Castle', 'Franz Kafka', 1926),
    ('I, Claudius', 'Robert Graves', 1934),
    ('Peter Pan', 'J.M. Barrie', 1904),
    ('A Confederacy of Dunces', 'John Kennedy Toole', 1980),
    ('The Razor''s Edge', 'W. Somerset Maugham', 1944),
    ('Lark Rise to Candleford', 'Flora Thompson', 1939),
    ('The Return of the Native', 'Thomas Hardy', 1878),
    ('A Portrait of the Artist as a Young Man', 'James Joyce', 1916),
    ('Heart of Darkness', 'Joseph Conrad', 1902),
    ('North and South', 'Elizabeth Gaskell', 1854),
    ('The Handmaid''s Tale', 'Margaret Atwood', 1985),
    ('What A Carve Up!', 'Jonathan Coe', 1994),
    ('The Godfather', 'Mario Puzo', 1969),
    ('Suite Francaise', 'Irene Nemirovsky', 2004),
    ('One Day in the Life of Ivan Denisovich', 'Alexander Solzhenitsyn', 1962),
    ('White Nights', 'Fyodor Dostoyevsky', 1848),
    ('Hard Times', 'Charles Dickens', 1854)